<html>
<head>
    <title>Code</title>
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.4.0/styles/atom-one-dark.min.css">
    <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.6/highlight.min.js"></script>
    <script>hljs.initHighlightingOnLoad();</script>
</head>
<body>
<span id="load_date">23</span>
<#--<span id="views_restriction">11312</span>-->
<span id="time_restriction">wewewe</span>
<#--<#if views??>-->
<#--    <span id="views_restriction"></span>-->
    <br><br>
<#--</#if>-->
<#--<#if time??>-->

<#--</#if>-->
<span id="views_restriction">${views}</span>
<br><br>


<pre id="code_snippet"><code>fre</code>
                </pre>
<#--<style>-->
<#--    pre{-->
<#--        border: 5px solid grey;-->
<#--        background: yellowgreen;-->
<#--        height: 75px ;-->
<#--        font-family: sans-serif;-->
<#--        width: 500px ;-->
<#--    }-->
<#--    #load_date{-->

<#--        color: green;-->
<#--        height: 75px ;-->
<#--        font-family: sans-serif;-->

<#--    }-->
<#--    /*#time_restriction{*/-->
<#--    /*    border: 5px solid grey;*/-->
<#--    /*    background: yellowgreen;*/-->
<#--    /*    height: 75px ;*/-->
<#--    /*    font-family: sans-serif;*/-->
<#--    /*    width: 500px ;*/-->
<#--    /*}*/-->
<#--</style>-->
</body>
</html>